### ISSUE TITLE
Problem installing server on Windows machine

### ISSUE THREAD

**Issue by smartchessguiapp** [yagu0/vchess#10]
Followed installation instructions in https://github.com/yagu0/vchess/tree/master/server/#vchess-server.

`git-fat pull` failed with:

![](https://i.imgur.com/EgSiSpQ.png)

tried under `cygwin`, received:

![](https://i.imgur.com/aSG0ogX.png)

**Comment by yagu0** [comment]
While I suspect the very first line isn't related to a git-fat issue, the others are. In fact it only works if I more-or-less manually add your SSH pubkey on my server (I had an automated script a few years ago... seems dysfunctional now, but it's not the point). This is clearly not an option for a repo opened to contributions by anyone. So I will:

1) Use git-lfs for the publicly "push-requestable" repo, here on Github. So from now you can just forget about the "git fat init / push / pull" steps --> I'll fix the README accordingly.

2) Still use git-fat (and fix my script in the meantime) for collaborators who would have read-write access to the repo. This is how I used to proceed and it worked well. I do that because I don't wanna depend on Github. My main repo is on my server.

=====

EDIT: that approach doesn't work. These large files managers are mutually exclusive (and this is understandable). So I only use git-fat now, and added a script to download the few binary objects for Github read-only users.
