### ISSUE TITLE
Static symlink breaks server under Windows

### ISSUE THREAD

**Issue by smartchessguiapp** [yagu0/vchess#15]
This is a minor issue, but I mention it anyway, so that the list of problems that prevented the app from working on Windows is complete.

Windows does not know how to deal with the symlink https://github.com/yagu0/vchess/blob/master/server/static , pointing to the folder holding favicon.ico, and this breaks the server.

I solved this by replacing the symlink with a folder and copied favicon.ico into this folder. I did not submit a pull request for this, as I felt this solution is a bit desperate and there may be a better one.

**Comment by yagu0** [comment]
Yes, in this case sorry but symlinks are cleaner. If Windows doesn't understand them because they are not in the Windows format, then yes copying files is an acceptable solution.

Actually on the prod server I have this dist folder in client, symlinked from the server folder. And an additionnal "fallback" folder on server where I copy the dist/ contents after each update. So during an update the server uses fallback/ and doesn't show the "Server updating please wait" message.
